// backend/crs / utils / constants.ts;
export const INTEGRATION_TYPES = {
  GMAIL: "GMAIL",
  GOOGLE_CALENDAR: "GOOGLE_CALENDAR",
  NOTION: "NOTION",
  SLACK: "SLACK",
  HUBSPOT: "HUBSPOT",
  LINEAR: "LINEAR",
  PHONE: "PHONE",
  GOOGLE_DRIVE: "GOOGLE_DRIVE",
  GOOGLE_SHEETS: "GOOGLE_SHEETS",
  GOOGLE_DOCS: "GOOGLE_DOCS",
} as const;

export const TASK_PRIORITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  URGENT: "URGENT",
} as const;

export const TASK_STATUSES = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const WORKFLOW_EXECUTION_STATUS = {
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
} as const;
